# Generated by Django 2.1.4 on 2018-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181220_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=20)),
                ('exam_title', models.CharField(max_length=40)),
                ('exam_subtitle', models.CharField(max_length=40)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Geometry', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
