# Generated by Django 2.2 on 2018-12-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181225_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examitem',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
