# Generated by Django 2.2 on 2018-12-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20181225_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examitem',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Question'),
        ),
    ]
