# Generated by Django 2.2 on 2018-12-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20181229_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
